# name: cd
# on:
#   push:
#     branches: [main]

# jobs:
#   cd:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: pnpm/action-setup@v2
#         with:
#           version: 8.6.8
#       - name: SSH to server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: root
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             cd /etc/project/valhalla
#             git pull origin main
#             export PATH=$PATH:/root/.nvm/versions/node/v18.16.1/bin
#             pnpm install & pnpm build
#             pm2 restart 0
